### ISSUE TITLE
add a relation closure to grab homologues

### ISSUE THREAD

**Issue by nathandunn** [nathandunn/galaxy-monarch-integration#1]
https://monarchinitiative.org/gene/NCBIGene:3973

https://solr.monarchinitiative.org/solr/golr/select?defType=edismax&qt=standard&indent=on&wt=csv&rows=100000&start=0&fl=object,object_label,object_taxon,object_taxon_label,relation,relation_label,evidence,evidence_label,source,is_defined_by,qualifier&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&facet.method=enum&csv.encapsulator=&csv.separator=%09&csv.header=true&csv.mv.separator=%7C&fq=subject_closure:%22NCBIGene:3973%22&fq=object_category:%22gene%22&fq=relation_closure:%22RO:HOM0000001%22&facet.field=subject_taxon_closure_label&facet.field=object_taxon_closure_label&q=*:*

**Comment by cmungall** [comment]
not totally sure what this ticket is for...

**Comment by nathandunn** [comment]
@cmungall   Its to grab Homologues for a gene.  I think its a nice use-case.  

<img width="1003" alt="screen shot 2016-06-08 at 9 25 49 am" src="https://cloud.githubusercontent.com/assets/751274/15902069/0125c670-2d5b-11e6-8ad6-ed9a53f50fc7.png">

**Comment by nathandunn** [comment]
<img width="1167" alt="screen shot 2016-06-08 at 11 02 04 am" src="https://cloud.githubusercontent.com/assets/751274/15905096/6a8a7b30-2d68-11e6-900c-df0e30100fb2.png">
<img width="756" alt="screen shot 2016-06-08 at 11 01 52 am" src="https://cloud.githubusercontent.com/assets/751274/15905095/6a8a4b92-2d68-11e6-8d1d-0421d852529f.png">

**Comment by nathandunn** [comment]
I think this is working adequately
